name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  generate-latest-changelog:
    name: Generate latest changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate latest changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --github-repo ${{ github.repository }}
  generate-full-changelog:
    name: Generate full changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Show CHANGELOG.md
        run: cat CHANGELOG.md

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ generate-latest-changelog, generate-full-changelog ]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          echo $RELEASE_VERSION
          npm version --no-git-tag-version $RELEASE_VERSION
          cat package.json
      - name: Save release notes to CHANGELOG.md
        run: echo "${{ needs.generate-full-changelog.outputs.release_body }}" > CHANGELOG.md
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'chore(release): update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md package.json
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "${{ needs.generate-latest-changelog.outputs.release_body }}"
          name: "Release v${{ env.RELEASE_VERSION }} 🐾"
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
