name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Update package version and publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Extract version from GitHub Release
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          echo $VERSION
          npm version --no-git-tag-version $VERSION
          cat package.json
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Display CHANGELOG.md
        run: |
          cat CHANGELOG.md
#      - name: Commit
#        run: |
#          git checkout <branch>
#          git config user.name 'github-actions[bot]'
#          git config user.email 'github-actions[bot]@users.noreply.github.com'
#          set +e
#          git add CHANGELOG.md
#          git commit -m "Update changelog"
#          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git <branch>

      # - name: Commit version bump
      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     git commit -am "chore: bump version to $VERSION"
      #     git push
      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v2
      #   with:
      #     pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com
